### ISSUE TITLE
page titles show some other paper's title

### ISSUE THREAD

**Issue by mtkft** [piemadd/windy-city-herald#1]
"Windy City Times" appears in tab titles and I can't post pictures of it until the GitHub mobile app starts to behave again (you don't need me to reproduce this: open any WCH page and look at the title of the tab)

**Comment by mtkft** [comment]
![Screenshot_20230618-004637.png](https://github.com/piemadd/windy-city-herald/assets/63917881/e9aa01c9-0dd5-4c83-829b-6d84b0c7e83c)

![Screenshot_20230618-004618.png](https://github.com/piemadd/windy-city-herald/assets/63917881/8efe21d8-7f07-4277-a73f-2daae0f62360)

**Comment by piemadd** [comment]
oh fuck oh shit

**Comment by piemadd** [comment]
Fixed in https://github.com/piemadd/windy-city-herald/commit/a98fa1628168df527bf04554cf304def07988f1f
